/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppRouteImport } from './routes/app'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as MarketingClaimRouteImport } from './routes/_marketing/claim'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingFaqRouteImport } from './routes/_marketing/faq'
import { Route as MarketingPrivacyPolicyRouteImport } from './routes/_marketing/privacy-policy'
import { Route as MarketingTermsOfServiceRouteImport } from './routes/_marketing/terms-of-service'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as AppCheckoutRouteImport } from './routes/app/checkout'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppQueueRouteImport } from './routes/app/queue'
import { Route as LiveIndexRouteImport } from './routes/live/index'
import { Route as LiveActivityRouteImport } from './routes/live/activity'
import { Route as LiveCheckoutRouteImport } from './routes/live/checkout'
import { Route as LiveProfileRouteImport } from './routes/live/profile'
import { Route as LiveQueueRouteImport } from './routes/live/queue'
import { Route as SalonIndexRouteImport } from './routes/salon/index'
import { Route as ApiAdminEmailRouteImport } from './routes/api/admin/email'
import { Route as AppSalonIdRouteImport } from './routes/app/salon.$id'
import { Route as LiveSalonIdRouteImport } from './routes/live/salon.$id'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingClaimRoute = MarketingClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqRoute = MarketingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyPolicyRoute = MarketingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTermsOfServiceRoute = MarketingTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => MarketingRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LiveRoute,
} as any)
const LiveActivityRoute = LiveActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LiveRoute,
} as any)
const LiveCheckoutRoute = LiveCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LiveRoute,
} as any)
const LiveProfileRoute = LiveProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LiveRoute,
} as any)
const LiveQueueRoute = LiveQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => LiveRoute,
} as any)
const SalonIndexRoute = SalonIndexRouteImport.update({
  id: '/salon/',
  path: '/salon/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailRoute = ApiAdminEmailRouteImport.update({
  id: '/api/admin/email',
  path: '/api/admin/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSalonIdRoute = AppSalonIdRouteImport.update({
  id: '/salon/$id',
  path: '/salon/$id',
  getParentRoute: () => AppRoute,
} as any)
const LiveSalonIdRoute = LiveSalonIdRouteImport.update({
  id: '/salon/$id',
  path: '/salon/$id',
  getParentRoute: () => LiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/about': typeof MarketingAboutRoute
  '/claim': typeof MarketingClaimRoute
  '/contact': typeof MarketingContactRoute
  '/faq': typeof MarketingFaqRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/app/activity': typeof AppActivityRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/live/activity': typeof LiveActivityRoute
  '/live/checkout': typeof LiveCheckoutRoute
  '/live/profile': typeof LiveProfileRoute
  '/live/queue': typeof LiveQueueRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/live/': typeof LiveIndexRoute
  '/salon/': typeof SalonIndexRoute
  '/api/admin/email': typeof ApiAdminEmailRoute
  '/app/salon/$id': typeof AppSalonIdRoute
  '/live/salon/$id': typeof LiveSalonIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof MarketingAboutRoute
  '/claim': typeof MarketingClaimRoute
  '/contact': typeof MarketingContactRoute
  '/faq': typeof MarketingFaqRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/app/activity': typeof AppActivityRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/live/activity': typeof LiveActivityRoute
  '/live/checkout': typeof LiveCheckoutRoute
  '/live/profile': typeof LiveProfileRoute
  '/live/queue': typeof LiveQueueRoute
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/live': typeof LiveIndexRoute
  '/salon': typeof SalonIndexRoute
  '/api/admin/email': typeof ApiAdminEmailRoute
  '/app/salon/$id': typeof AppSalonIdRoute
  '/live/salon/$id': typeof LiveSalonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/claim': typeof MarketingClaimRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/faq': typeof MarketingFaqRoute
  '/_marketing/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/_marketing/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/app/activity': typeof AppActivityRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/live/activity': typeof LiveActivityRoute
  '/live/checkout': typeof LiveCheckoutRoute
  '/live/profile': typeof LiveProfileRoute
  '/live/queue': typeof LiveQueueRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/live/': typeof LiveIndexRoute
  '/salon/': typeof SalonIndexRoute
  '/api/admin/email': typeof ApiAdminEmailRoute
  '/app/salon/$id': typeof AppSalonIdRoute
  '/live/salon/$id': typeof LiveSalonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/live'
    | '/about'
    | '/claim'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/app/activity'
    | '/app/checkout'
    | '/app/profile'
    | '/app/queue'
    | '/live/activity'
    | '/live/checkout'
    | '/live/profile'
    | '/live/queue'
    | '/admin/'
    | '/app/'
    | '/live/'
    | '/salon/'
    | '/api/admin/email'
    | '/app/salon/$id'
    | '/live/salon/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/claim'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/app/activity'
    | '/app/checkout'
    | '/app/profile'
    | '/app/queue'
    | '/live/activity'
    | '/live/checkout'
    | '/live/profile'
    | '/live/queue'
    | '/'
    | '/admin'
    | '/app'
    | '/live'
    | '/salon'
    | '/api/admin/email'
    | '/app/salon/$id'
    | '/live/salon/$id'
  id:
    | '__root__'
    | '/_marketing'
    | '/app'
    | '/live'
    | '/_marketing/about'
    | '/_marketing/claim'
    | '/_marketing/contact'
    | '/_marketing/faq'
    | '/_marketing/privacy-policy'
    | '/_marketing/terms-of-service'
    | '/app/activity'
    | '/app/checkout'
    | '/app/profile'
    | '/app/queue'
    | '/live/activity'
    | '/live/checkout'
    | '/live/profile'
    | '/live/queue'
    | '/_marketing/'
    | '/admin/'
    | '/app/'
    | '/live/'
    | '/salon/'
    | '/api/admin/email'
    | '/app/salon/$id'
    | '/live/salon/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LiveRoute: typeof LiveRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  SalonIndexRoute: typeof SalonIndexRoute
  ApiAdminEmailRoute: typeof ApiAdminEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/claim': {
      id: '/_marketing/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof MarketingClaimRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faq': {
      id: '/_marketing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof MarketingFaqRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy-policy': {
      id: '/_marketing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof MarketingPrivacyPolicyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/terms-of-service': {
      id: '/_marketing/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof MarketingTermsOfServiceRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/live/': {
      id: '/live/'
      path: '/'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof LiveRoute
    }
    '/live/activity': {
      id: '/live/activity'
      path: '/activity'
      fullPath: '/live/activity'
      preLoaderRoute: typeof LiveActivityRouteImport
      parentRoute: typeof LiveRoute
    }
    '/live/checkout': {
      id: '/live/checkout'
      path: '/checkout'
      fullPath: '/live/checkout'
      preLoaderRoute: typeof LiveCheckoutRouteImport
      parentRoute: typeof LiveRoute
    }
    '/live/profile': {
      id: '/live/profile'
      path: '/profile'
      fullPath: '/live/profile'
      preLoaderRoute: typeof LiveProfileRouteImport
      parentRoute: typeof LiveRoute
    }
    '/live/queue': {
      id: '/live/queue'
      path: '/queue'
      fullPath: '/live/queue'
      preLoaderRoute: typeof LiveQueueRouteImport
      parentRoute: typeof LiveRoute
    }
    '/salon/': {
      id: '/salon/'
      path: '/salon'
      fullPath: '/salon/'
      preLoaderRoute: typeof SalonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email': {
      id: '/api/admin/email'
      path: '/api/admin/email'
      fullPath: '/api/admin/email'
      preLoaderRoute: typeof ApiAdminEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/salon/$id': {
      id: '/app/salon/$id'
      path: '/salon/$id'
      fullPath: '/app/salon/$id'
      preLoaderRoute: typeof AppSalonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/live/salon/$id': {
      id: '/live/salon/$id'
      path: '/salon/$id'
      fullPath: '/live/salon/$id'
      preLoaderRoute: typeof LiveSalonIdRouteImport
      parentRoute: typeof LiveRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingClaimRoute: typeof MarketingClaimRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingFaqRoute: typeof MarketingFaqRoute
  MarketingPrivacyPolicyRoute: typeof MarketingPrivacyPolicyRoute
  MarketingTermsOfServiceRoute: typeof MarketingTermsOfServiceRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingClaimRoute: MarketingClaimRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingFaqRoute: MarketingFaqRoute,
  MarketingPrivacyPolicyRoute: MarketingPrivacyPolicyRoute,
  MarketingTermsOfServiceRoute: MarketingTermsOfServiceRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQueueRoute: typeof AppQueueRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSalonIdRoute: typeof AppSalonIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppProfileRoute: AppProfileRoute,
  AppQueueRoute: AppQueueRoute,
  AppIndexRoute: AppIndexRoute,
  AppSalonIdRoute: AppSalonIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LiveRouteChildren {
  LiveActivityRoute: typeof LiveActivityRoute
  LiveCheckoutRoute: typeof LiveCheckoutRoute
  LiveProfileRoute: typeof LiveProfileRoute
  LiveQueueRoute: typeof LiveQueueRoute
  LiveIndexRoute: typeof LiveIndexRoute
  LiveSalonIdRoute: typeof LiveSalonIdRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveActivityRoute: LiveActivityRoute,
  LiveCheckoutRoute: LiveCheckoutRoute,
  LiveProfileRoute: LiveProfileRoute,
  LiveQueueRoute: LiveQueueRoute,
  LiveIndexRoute: LiveIndexRoute,
  LiveSalonIdRoute: LiveSalonIdRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LiveRoute: LiveRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  SalonIndexRoute: SalonIndexRoute,
  ApiAdminEmailRoute: ApiAdminEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
