name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: npm install



      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Android AAB
        working-directory: android
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Snepr-App-Bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
